### PR TITLE
feat: added player controller

### PR DESCRIPTION
**Pull request by nmspackman**
- Player can move in 8 axis
- Player can sneak, walk, and run
- Movement is normalized

[NOTE] We can tweak the inputs to trigger the movement type and adjust the speed values.

### CODE REVIEW

**Comment by CaldwellYSR** [comment]
I'm not convinced we need to be using Physics here to move the character. I like the Rigidbody2D for collisions but I think we can move it with `RigidBody2D.MovePosition/1` instead of velocity updates. I like the Enum/Dictionary combo for defining the difference speeds. Eventually we want to use `Input.GetButton` instead of `GetKey` though.

**Comment by nmspackman** [comment]
That makes sense - I'll update to use position instead of physics. I'll also switch to using `Input.GetButton` now. Then we can update some mapping as needed.

[NOTE] see https://docs.unity3d.com/ScriptReference/Rigidbody.MovePosition.html and https://docs.unity3d.com/ScriptReference/Input.GetButton.html

**Review by CaldwellYSR — CHANGES_REQUESTED** [review]
Wasn't sure how reviews worked... just doing this for formality see previous comment for changes.

**Comment by daemyonc** [comment]
It's cool. I like it. Not sure if you meant to but I like the fact that you can be sneaking with Left Shift and still Run if you hold down Space also.

**Review by CaldwellYSR — APPROVED** [review]

**Pull request merged**
