### PR TITLE
Tilemap with Random brush and 3 custom terrain sprites

### PR DESCRIPTION
**Pull request by daemyonc**
Can't use SVG in Unity 2020 so they are PNGs. Open Terrain Tilemap and paint on the Grid in TestLevel. The script is from Unity 2d extras official/unofficial package. Might have to select Random Brush in Tile Palette.

### CODE REVIEW

**Review by CaldwellYSR — APPROVED** [review]
I don't see any conflicts and I was able to load the scene no problem. Might be worthwhile to think about splitting some of the files into folders in the long run but I don't see any issues merging this.

**Comment by CaldwellYSR** [comment]
It can't auto-merge... did you rebase your branch on master before you pushed?

**Comment by daemyonc** [comment]
I did not rebase.

**Comment by CaldwellYSR** [comment]
You need to rebase on master and force push then this will be able to
merge.

**Pull request merged**
